### ISSUE TITLE
Put the config file in the output directory instead of the current directory

### ISSUE THREAD

**Issue by ckhroulev** [pism/pism-gris#1]
@aaschwanden: Right now this script (see the code below) puts the generated config file in the current directory. Do you think it would make more sense to put it in the output directory specified using the command-line option `--o_dir`? (I think it would.)

https://github.com/pism/pism-gris/blob/5d98cd564ef29e92d6a251b7cdbf70f75e22c308/stability/lhs_ensemble.py#L149-L153

**Comment by aaschwanden** [comment]
Works for me. It’s barely used anyways as I use the command line options. 

Now that I think about it (and because now we have a one to one mapping of parameter names) we could use the configuration file instead of putting everything into the run script
